Write cloud function to fetch data by NP slug
hollowverse-archive/hollowverse pull request #125
Opened 2017-07-09 14:44 UTC by forabi

This PR introduces a new cloud function, `fetchDataBySlug`, which takes a slug for NP (the part after `/notable-person/`) and fetches the data for that NP. This function also has a client-side equivalent that requests data from that function by sending a GET request with the `slug` parameter as the URL query:

```
GET https://us-central1-hollowverse-c9cad.cloudfunctions.net/fetchDataBySlug?slug=Tom_Hanks
```

The data, as well as the mapping `slug => ID` is already in place for Tom Hanks. The saga `requestNotablePerson` is rewritten to use the new function and the `notablePerson` component is configured properly to read the slug from the URL and dispatch `requestNotablePerson`. So the following route is actually displayed properly:

```
/notable-person/Tom_Hanks
```

This PR also reduces the `vendor` bundle size from around 620KB to 542KB by importing only the necessary functionality from Firebase (authentication and database).

## Things that still need to be done before meging
* Add a polyfill for `fetch()` or use a lightweight wrapper around `XMLHttpRequest` like [`got`](https://github.com/sindresorhus/got).
* How should we handle CORS? Cloud functions are hosted on `*.cloudfunctions.net` so they belong to an origin different from our origin. To workaround that, we currently allow all CORS requests, but this also allows any other website to call our cloud function. On the other hand, allowing only `*.hollowverse` origin would make local development inconvenient as the app is served from `localhost` and this origin is not allowed, and Chrome does not allow access to CORS responses from `localhost` even if it is specified explicitly in the `Access-Control-Allow-Origin` header.

2017-07-09 17:18 UTC, msafih commented on client/src/index.tsx
> +        <Route exact path="/notable-person/:slug" component={NotablePerson} />
We need to put the slug at the root level, so that `https://hollowverse.com/Tom_Hanks` will work.

2017-07-09 17:18 UTC, msafih commented on client/src/store/types.ts
> - * but it still requiers that the type of action is one of
VS Code should spell check comments 😄

2017-07-09 17:18 UTC, msafih commented on client/src/store/types.ts
> +  [// tslint:disable-next-line no-suspicious-comment
Is this Prettier's doing?

2017-07-09 17:18 UTC, msafih commented on functions/index.js
> +  cors(req, res, () => {
I assume Firebase back-end uses this `cors` as an Express middleware? Will this `cors` call be duplicated in many of our Firebase CF calls?

2017-07-09 17:18 UTC, msafih commented on functions/index.js
> +});
Will we convert this file to TypeScript and to all the good stuff we currently do inside `client/`?

2017-07-09 17:18 UTC, msafih commented on client/src/utils/utils.ts
> +  return (ev as EventWithQuoteSchema).quote !== undefined;
Could you tell me why you need to do `is` and then assert `as`?

2017-07-09 17:24 UTC, msafih commented
> Add a polyfill for `fetch()` or use a lightweight wrapper around `XMLHttpRequest` like [`got`](https://github.com/sindresorhus/got).

I'm okay with either approach.

> How should we handle CORS? Cloud functions are hosted on `*.cloudfunctions.net` so they belong to an origin different from our origin. To workaround that, we currently allow all CORS requests, but this also allows any other website to call our cloud function. On the other hand, allowing only `*.hollowverse` origin would make local development inconvenient as the app is served from `localhost` and this origin is not allowed, and Chrome does not allow access to CORS responses from `localhost` even if it is specified explicitly in the `Access-Control-Allow-Origin` header.

We can whitelist `*.hollowverse` and use [this Chrome extension](https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi?hl=en) for local development. But, you know, I'm okay with whitelisting `*.*`. We can go with `*.*` until we see an actual problem.

2017-07-09 17:35 UTC, forabi commented on client/src/utils/utils.ts
> +  return (ev as EventWithQuoteSchema).quote !== undefined;
This is an advanced feature of TypeScript, called a "type guard".

The problem with the `EventSchema` is that it is an intersection type, which could or could not have a quote. Trying to access the `quote`, `sourceUrl` or `sourceName` properties is not safe so TypeScript does not allow it. So we need a way to tell TypeScript that we can provide a guarantee that an event is an `EventWithQuoteSchema`. This is what type guards do.

This basically says to TypeScript: if this function returns `true`, then you can assume that `ev` is guaranteed to be an event with a quote, so you can stop complaining about the type not having a `quote`, `sourceUrl` or `sourceName` properties.

Now because TypeScript performs control-flow analysis, it can see that when this type guard is used in an if statement, then the type of event in the if body is guaranteed to be an `EventWithQuoteSchema`, so it can correctly narrow down to this type.

The type cast is needed for the same reason, we cannot access `quote` without assuming that the type is an `EventWithQuoteSchema`.

2017-07-09 17:35 UTC, forabi commented on functions/index.js
> +});
Yes I plan to, I just wanted to make sure it works as this is my first experience with CFs.

2017-07-09 17:40 UTC, forabi commented
@msafih It seems to be [supported](http://caniuse.com/#search=fetch) in all evergreen browsers. Are we targeting Safari 9? I remember testing one of my projects on an iPad with Safari 9 and it wouldn't load because `fetch` was not supported.

OK, let's just keep access allowed for all origins for now.

2017-07-09 17:43 UTC, forabi commented on functions/index.js
> +  cors(req, res, () => {
Yes it looks like we will have to use it in every HTTP function. In fact, [the documentation](https://firebase.google.com/docs/functions/http-events) has an example that uses the same `cors` module.

2017-07-09 17:44 UTC, forabi commented on client/src/store/types.ts
> +  [// tslint:disable-next-line no-suspicious-comment
Yes, it is clearly a bug. I can fix it and commit with `--no-verify` to disable pre-commit prettier hook.

2017-07-09 17:48 UTC, msafih commented on client/src/utils/utils.ts
> +  return (ev as EventWithQuoteSchema).quote !== undefined;
Cool. That makes sense. So what's the difference between using an intersection type and setting `quote`, `sourceUrl` and `sourceName` as optional keys with `?`?

2017-07-09 17:59 UTC, msafih commented
Ah, freaking Apple with their browser support. How about we only target the latest Safari version?

2017-07-09 18:10 UTC, forabi commented on client/src/utils/utils.ts
> +  return (ev as EventWithQuoteSchema).quote !== undefined;
Using an intersection type means that the type will either have all the three properties or none of them. Making each one optional does not mean that the three properties go together.

2017-07-09 18:11 UTC, forabi commented on client/src/utils/utils.ts
> +  return (ev as EventWithQuoteSchema).quote !== undefined;
Using an intersection type means that the type will either have all the three properties or none of them. Making each one optional does not mean that the three properties go together.

2017-07-09 18:13 UTC, forabi commented
Okay, let's go with Safari >= 10 :smiley:

2017-07-09 18:23 UTC, msafih commented on client/src/pages/notablePerson/events.tsx
> +import { sortByDescending, doesEventHaveQuote } from 'utils/utils';
Would be nice to have a lint rule against this

2017-07-09 18:39 UTC, forabi commented on client/src/pages/notablePerson/events.tsx
> +import { sortByDescending, doesEventHaveQuote } from 'utils/utils';
I tried [this](https://github.com/vrsource/vrsource-tslint-rules#no-duplicate-imports) but it seems to be incompatible with TSLint >= 5.

2017-07-10 17:22 UTC, forabi commented
@msafih I think this is ready

2017-07-11 03:50 UTC, wholesomedev requested changes
Left a couple of comments, but looks good otherwise 👍

2017-07-11 03:50 UTC, msafih commented on client/src/pages/notablePerson/events.tsx
> +        if (doesEventHaveQuote(event)) {
I thought some more about this. And I think we should update our Product Description to specify that each event must contain a quote. So we shouldn't have this case where we have an event without a quote.

I'm worried if we allow events without quotes people will just be posting their opinions on things?

2017-07-11 03:50 UTC, msafih commented on functions/src/.gitignore
> +yarn.lock
Hmmm, why do we have a `.gitignore` inside `functions/src/`?

2017-07-11 04:35 UTC, forabi commented on functions/src/.gitignore
> +yarn.lock
Firebase CF does not use yarn, so package versions may be different from our local version, so I thought we should not lock our CF dependencies as this may give a false sense of security.

2017-07-11 04:37 UTC, forabi commented on functions/src/.gitignore
> +yarn.lock
I can also ignore this file from `<root>/.gitignore`.

2017-07-11 04:40 UTC, msafih commented on functions/src/.gitignore
> +yarn.lock
Oh, I didn't know it was possible to have several `.gitignore` files in different folders. TIL.

I think maybe it's better to keep one `.gitignore` file in the root?

2017-07-11 04:46 UTC, forabi commented on client/src/pages/notablePerson/events.tsx
> +        if (doesEventHaveQuote(event)) {
This will make our code simpler. I will rewrite this later today and update the wiki.

2017-07-11 14:18 UTC, forabi commented on client/src/pages/notablePerson/events.tsx
> +        if (doesEventHaveQuote(event)) {
OK, I wrote this code. It turns out quotes are already documented to be required for events. It was an oversight on my part. I was trying to fit the old data into the new model.

2017-07-12 02:49 UTC, wholesomedev submitted a review, later dismissed

2017-07-12 03:11 UTC, wholesomedev approved these changes

2017-07-12 03:11 UTC, merged