Implement server-side logging with Sumo Logic
hollowverse-archive/hollowverse pull request #143
Opened 2017-08-12 11:04 UTC by forabi

Closes #9

2017-08-12 15:04 UTC, forabi commented
Testing locally, this is already working and logs are showing Sumo Logic in dashboard:
![screenshot_20170812_180331](https://user-images.githubusercontent.com/1012761/29241768-92077bf4-7f88-11e7-9389-3383705cee23.png)

2017-08-12 18:53 UTC, forabi commented
I submitted the type definitions to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18898

2017-08-12 18:56 UTC, forabi commented
@msafih Based on earlier discussion on Discord, should I go ahead and implement the API endpoint for logging?

2017-08-13 16:05 UTC, msafih commented on custom-typings/sumo-logger.d.ts
> +}
This file and folder should be camelCased.

2017-08-13 16:27 UTC, forabi commented on custom-typings/sumo-logger.d.ts
> +}
I think it needs to match the NPM package name in order for TS to pick it up. This should be removed once https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18898 is merged anyway.

2017-08-13 16:29 UTC, forabi commented on custom-typings/sumo-logger.d.ts
> +}
I've just updated the folder name.

2017-08-14 17:11 UTC, forabi commented
> * [ ] Create a different _sourceCategory for each deployed version.

I would like to implement this, but it looks like App Engine does not expose the version information to custom runtimes. I have SSH into the container and there are no environment variables that have the version name. The Node.js runtime, however, [has this info](https://cloud.google.com/appengine/docs/flexible/nodejs/runtime). I'm thinking we should probably move to the Node.js runtime, since we are not using any native packages in the default service. But that means we are moving away from our approach to use Docker everywhere. I'm not sure. What do you think, @msafih?

2017-08-15 15:02 UTC, forabi commented
We will have to merge https://github.com/hollowverse/hollowverse-docker/pull/7 first.

2017-08-17 03:01 UTC, wholesomedev requested changes

2017-08-17 03:01 UTC, wholesomedev commented on secrets/README.md
> +A JSON file used containing the Colllector ID used to instantiate a `SumoLogger` instance on the server, to send logs to [Sumo Logic](https://www.sumologic.com/). The HTTP collector ID should be trea
Can you link [Collector ID](https://help.sumologic.com/Start-Here/02Getting-Started/Glossary#section_2)

2017-08-17 03:01 UTC, wholesomedev commented on secrets/README.md
> +    openssl aes-256-cbc -in ./sumo.json -out sumo.json.enc -K $ENC_KEY_SUMO -iv $ENC_IV_SUMO -base64
Isn't `sumo.json.enc` `-in` and `sumo.json` `-out`?

2017-08-17 03:01 UTC, wholesomedev commented on secrets/README.md
> +We think it is better to have a separate encryption key for each file, because it allows us to add secrets without having to re-encrypt the previously encrypted files, which means we do not have to k
This README is very useful 👍

I think it's better that we're using the `openssl` CLI rather than Travis's. It's a more standard way of doing it.

On a side note: I'd like to create a knowledge-base for Hollowverse where we document certain decisions we make and their reasons, like this one about `openssl` vs Travis CLI. It can be a quick and dirty brain-dump type of content.

Edit: I've done some research on this knowledge-base thing. There doesn't seem to be a good solution for it. There are services like Confluence but they are paid and very far from our workflow. I don't know if a good solution to this exists.

2017-08-17 03:01 UTC, msafih commented on redirectionProxy/redirectionProxy.ts
> +server.use('/log', logEndpoint);
What is your plan for the redirectionProxy? I feel like this file will end up being our app entry point 😄

2017-08-17 03:01 UTC, msafih commented on server/src/logger/logger.ts
> +export function log<T extends LogType>(type: T, data: LogPayload<T>) {
I studied TypeScript briefly before I started this project and it was very interesting. Now I see all these tricks you have with generics and I have no idea what you're doing lol

I gotta brush up on my TypeScript again in the future. I'll see if I can push them to use TypeScript at work so I don't get rusty like that.

2017-08-17 03:01 UTC, msafih commented on server/src/server.ts
> +const PORT = process.env.STATIC_SEVER_PORT || 3000;
`SERVER` is misspelled. 

Are we using this static server for anything? What port is it listening on and is that port configured on App Engine some where?

2017-08-17 03:17 UTC, msafih commented on server/src/logger/logEndpoint.ts
> +logEndpoint.post('/', async (req, res) => {
This `async` is not necessary.

2017-08-17 05:35 UTC, forabi commented on server/src/logger/logEndpoint.ts
> +logEndpoint.post('/', async (req, res) => {
Fixed

2017-08-17 05:38 UTC, forabi commented on server/src/server.ts
> +const PORT = process.env.STATIC_SEVER_PORT || 3000;
Fixed.

The static server is started on port 3000 (because `STATIC_SEVER_PORT` is always `undefined`) and the proxy server redirects the `newPaths` and `staticFiles` to proxy to `localhost:3000` (https://github.com/hollowverse/hollowverse/blob/master/redirectionProxy/redirectionProxy.ts#L12).

However, there is no need for the new static server as we are not currently routing any pages to the new app.

2017-08-17 05:40 UTC, forabi commented on server/src/logger/logger.ts
> +export function log<T extends LogType>(type: T, data: LogPayload<T>) {
This is simply to make sure that the payload type corresponds to the intended log event of type `T`, and we get autocompletion and stuff.

2017-08-17 05:41 UTC, forabi commented on redirectionProxy/redirectionProxy.ts
> +server.use('/log', logEndpoint);
Yes, #145 should move the redirection proxy to `./server/src` and make it the entry point.

2017-08-17 05:43 UTC, forabi commented on secrets/README.md
> +    openssl aes-256-cbc -in ./sumo.json -out sumo.json.enc -K $ENC_KEY_SUMO -iv $ENC_IV_SUMO -base64
Fixed, actually I was missing the `-pass` flag too. I sent https://github.com/hollowverse/hollowverse-docker/pull/8 to fix the decryption in the env image too.

2017-08-17 05:43 UTC, forabi commented on secrets/README.md
> +A JSON file used containing the Colllector ID used to instantiate a `SumoLogger` instance on the server, to send logs to [Sumo Logic](https://www.sumologic.com/). The HTTP collector ID should be trea
Done

2017-08-17 17:34 UTC, wholesomedev approved these changes

2017-08-17 17:34 UTC, merged