Migrate to AWS Elastic Beanstalk
hollowverse-archive/hollowverse pull request #176
Opened 2017-09-07 10:30 UTC by forabi

* Remove Google App Engine files
* Add the configuration file for AWS CodeBuild (`buildspec.yml`).
* Rewrite `deploy.js` to work with CodeBuild and Travis: it turns out we will have to use Travis for PRs because CodeBuild only supports branch updates. Still, using CodeBuild gives us some nice integration features with AWS services. For example: 
  * we can store the encryption passwords securely in AWS Params Store and use them in CodeBuild to decrypt the secrets
  * we don't have to install the AWS EB CLI tool in the environment image or write our custom logic to bundle and deploy the build files. CodePipeline integrates with CodeBuild to automate this process completelty
  * using CodeBuild allows us to use CodePipeline to stage and review testing versions easily before they are pushed to production

I've configured CodeBuild to build the `master` branch of this repo. CodePipeline will watch the repo, trigger CodeBuild, and deploy the changes automatically to Elastic Beanstalk.

2017-09-07 16:27 UTC, forabi commented
@msafih This is ready. Once merged, CodePipeline should automatically deploy to EB.

2017-09-08 03:30 UTC, wholesomedev requested changes

2017-09-08 03:30 UTC, msafih commented on deploy.js
>    if (isPullRequest === false) {
I'm confused by this part. 

```js
if (isPullRequest === false) { console.info('Skipping deployment commands in PRs'); }
```

2017-09-08 03:30 UTC, msafih commented on deploy.js
> +    isDeployment = true;
If `isPullRequest` is `true` and every secret is defined, then the execution will come to this branch. Is this what we want?

2017-09-08 03:30 UTC, msafih commented on server/src/health.ts
> -export { health };
How did it feel deleting this file? lol

2017-09-08 10:50 UTC, forabi commented on deploy.js
>    if (isPullRequest === false) {
Oops. Fixed.

2017-09-08 10:58 UTC, forabi commented on server/src/health.ts
> -export { health };
![Tears of joy](https://media.giphy.com/media/MziKDo6gO7x8A/giphy.gif)

2017-09-08 14:35 UTC, msafih commented on server/src/health.ts
> -export { health };
😂

2017-09-08 14:36 UTC, wholesomedev approved these changes

2017-09-08 15:41 UTC, merged