Deployment
hollowverse-archive/hollowverse pull request #22
Opened 2017-04-06 03:45 UTC by msafih

I have initted a Firebase project at the root of our repo. Basically, I followed the Firebase hosting instructions (https://firebase.google.com/docs/hosting/) and that asked me to install the Firebase CLI (https://firebase.google.com/docs/cli/) and init a project. I did that and here's the structure that they gave us:

* `/public` is gonna contain all the static assets (JS, CSS, HTML, images, etc)
* `/functions` is gonna contain [Firebase Cloud Functions](https://firebase.google.com/docs/functions/)

(There are also other dot files and configuration files that they added.)

### Domain name

My plan is to create the domain name **`x.hollowverse.com`** and have that be our home for now. Then I want to create a deploy script. 

### Deploy script

The job of the deploy script is the following:

1. Create the JavaScript bundle and put it in `/public`
1. Create `styles.css` and put it in `/public`
1. Copy `index.html` from `/client` to `/public`
1. Run `firebase deploy` (that will upload `/public` and `/functions` to Firebase)

The command to run the deploy script will be **`npm run deploy`**.

I'm thinking of using ShellJS to perform the tasks of the deploy script. I'd like to avoid using Grunt or Gulp if possible.

### Other notes

For now we don't have any Cloud Functions, but I think it should be part of our design guidelines that any code that can be run on the server, should be run on the server. For example, we have code in `vendor.firebase.ts` that handles creation of new user that can be moved server-side. We should move it. I've added that bit to our README.

It should also be noted that the deployment process will change before we launch V1. We will need an actual Node server to do server-side rendering and we'll need automatic deployment of `master` through Travis CI. But let's make these tasks part of another PR.

### Remaining tasks

- [ ] Setup domain name
- [ ] Create a build script
- [ ] Add deployment instructions to README

2017-04-07 01:50 UTC, msafih commented
I've setup the domain name. `https://x.hollowverse.com`. But I haven't deployed any content to it yet.

2017-04-08 09:17 UTC, deltaidea commented
I've searched a bit and it looks like you're right, there's no way to do server-side rendering without a dedicated Node.JS server.

I'd propose using Heroku since it's so easy to set up, has a great free plan with unlimited apps for experiments, and I have experience with it. We can switch to a less hipster hosting once there's a noticeable load from users.

2017-04-08 09:18 UTC, deltaidea requested changes
Lemme configure Travis CI, Heroku, do a full deploy and then we can merge with confidence.

2017-04-08 16:21 UTC, msafih commented on README.md
> +* Deploy to Firebase: `npm run deploy` - requires access to the Firebase project
I think you need to have the `firebase-tools` installed and you have to be logged in as described here https://firebase.google.com/docs/cli/

2017-04-08 16:38 UTC, msafih commented
@deltaidea Can we do the Node.js, server-side rendering, and Travis CI setup as part of other PRs?

Regarding Heroku, I think it is a good choice, but since we're already on Google Cloud platform, I propose we stay with it. I'm not familiar with Google Cloud platform, but eventually we'll have to get familiar with it, so we might as well do it now. Things will simpler if we do not add another service provider to the mix.

2017-04-08 16:40 UTC, msafih commented
So I think with your latest commits, this PR is ready to review and merge.

2017-04-08 17:42 UTC, deltaidea approved these changes

2017-04-08 17:42 UTC, deltaidea commented
Agreed on all points. 👍 
Check the last two commits and go ahead and merge this bad boy.

2017-04-08 19:57 UTC, merged