pull in old work for notablePerson page
hollowverse-archive/hollowverse pull request #75
Opened 2017-05-09 20:18 UTC by levsthings

[x] Pull in the old work done for Notable Person page.
[ ] Rewrite existing styles in aphrodite.
[ ] Finish Notable Person page.

Closes #58 .

2017-05-10 23:20 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.tsx
> +  notablePersonLabels: [string]
Is this an alternative way to type an array of strings? The way I know is `string[]`

2017-05-10 23:59 UTC, levsthings commented on client/src/pages/notablePerson/notablePerson.tsx
> +  notablePersonLabels: [string]
It's actually the tuple syntax, I had a number in there as well but removed it afterwards. But string stayed. :)

2017-05-11 03:17 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.tsx
> +  notablePersonLabels: [string]
Ah, TIL

2017-05-11 03:18 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.styles.ts
> +    maxWidth: '150px',
Isn't it better for this to be a percentage?

2017-05-14 17:00 UTC, wholesomedev requested changes

2017-05-14 17:00 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.styles.ts
> +    maxWidth: '150px',
Should this be a percentage?

2017-05-14 17:00 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.styles.ts
> +    margin: '0.8rem 0.8rem',
Will `margin` overwrite `marginTop`?

2017-05-14 17:00 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.tsx
> +            <h1 className={css(styles.notablePersonTitle)}>Religion, Politics, and ideas of...</h1>
Can we sentence-case this?

2017-05-14 18:04 UTC, levsthings commented on client/src/pages/notablePerson/notablePerson.styles.ts
> +    margin: '0.8rem 0.8rem',
Good catch, it was a leftover property from the early implementation.

2017-05-14 18:13 UTC, wholesomedev approved these changes

2017-05-14 18:16 UTC, msafih commented
LGTM! I've updated the PR message to remove the "Close" keyword because I think we need to keep #58 open until we have fully completed the Notable Person page, including having it work against an actual backend.

2017-05-14 18:16 UTC, merged