Build 'ContactUs Form' Page
hollowverse-archive/hollowverse pull request #76
Opened 2017-05-11 22:35 UTC by JavaScriptErika

Goals:
- [x] Create a page with its own route
- [x] Include email and message form fields
- [ ] Write logic for React to collect data on submit
- [ ] Deliver data async
- [ ] Add/write styles in aphrodite

Closes #14

2017-05-18 03:55 UTC, wholesomedev requested changes

2017-05-18 03:55 UTC, msafih commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +              onChange={({target: {value}}) => this.handleEmailInputChange(value)}
I think we will be doing this in a lot of our components. Maybe it would make sense for us to create our own common `input` component, call it `Input` and make it delegate to the native `input` component but with an additional prop called `onChangeText` which accepts a callback that expects to be given the text directly?

2017-05-18 03:55 UTC, msafih commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +              name='emailAddress'
We don't need `id` or `name` props

2017-05-18 03:55 UTC, msafih commented on client/src/index.tsx
> +        {<Route path='/contactUs' component={ContactUsForm}/>}
Can you snake-case the path?

2017-05-18 03:55 UTC, msafih commented on client/src/redux/actions.ts
> +  setEmailInputValue: (payload: string | boolean) => ({type: 'setEmailInputValue', payload}),
Why would the email address be a boolean?

2017-05-18 03:55 UTC, msafih commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +              name='userMessage'
We don't need `id` and `name` props here either

2017-05-18 04:03 UTC, msafih commented
@JavaScriptErika I've left some comments on your work so far. Regarding the next step, how about this: instead of doing form validation, how about you disable the submit button until the form state is valid?

A valid form state would be:

1. A valid email address
1. At least one word in the textarea

When these two conditions are met, the submit button is active. Otherwise, it's inactive.

2017-05-18 07:09 UTC, JavaScriptErika commented on client/src/redux/actions.ts
> +  setEmailInputValue: (payload: string | boolean) => ({type: 'setEmailInputValue', payload}),
It should not be. I was experimenting and forgot to remove it before committing, thank you for catching that.

2017-05-18 07:09 UTC, JavaScriptErika commented on client/src/index.tsx
> +        {<Route path='/contactUs' component={ContactUsForm}/>}
Yes!

2017-05-18 07:10 UTC, JavaScriptErika commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +              name='userMessage'
Great, I'll remove them.

2017-05-18 07:10 UTC, JavaScriptErika commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +              name='emailAddress'
Removing them now

2017-05-18 07:21 UTC, JavaScriptErika commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +              onChange={({target: {value}}) => this.handleEmailInputChange(value)}
I'll get to working on that, it will make the code cleaner, too.

2017-05-18 07:28 UTC, JavaScriptErika commented
Thank you for your feedback @msafih . It's interesting you mentioned the disabling/enabling of the submit button because it was a thought that crossed my mind recently. 

The validity of the email address is taken care of with html5, and assigning the input as 'type=email', is that fine or are there any additional ways you'd like me to implement that?

2017-05-21 10:52 UTC, levsthings requested changes

2017-05-21 10:52 UTC, levsthings commented on client/src/redux/actions.ts
> +  setSubmitFormValues: (payload: object) => ({type: 'setSubmitFormValues', payload}),
Let's not use the object keyword as a type, the object in question needs to be typed. For temporary situations, use `payload: {}` instead.

2017-05-21 15:13 UTC, wholesomedev requested changes

2017-05-21 15:13 UTC, wholesomedev commented on client/src/utils/utils.ts
> +export function isValidEmail(email: string): boolean {
FYI: TypeScript can infer the return type of the function, you don't have to specify it. Though specifying it probably enhances readability.

2017-05-21 15:13 UTC, msafih commented on client/src/utils/utils.ts
> +  const ePattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/
I prefer to avoid abbreviations in code, so `emailPattern` would be a better name here. (Though abbreviations are okay when it's a common conventional one, like `minLength` or `maxLength`.)

The other thing is that this email pattern is too restrictive. If I'm reading it correctly, I don't think it accepts `msafi+hollowverse@msafi.com`, which is the email I use for this project :)

It also doesn't accept non-English characters.

I think a better way to validate email is something like:

```
anyCharacterEvenNonEnglish@anyCharacterEverNonEnglish.AnyCharacterEvenNonEnglish
```

2017-05-21 15:13 UTC, msafih commented on client/src/utils/utils.ts
> +  if (message.trim().length !== 0 && message.length > minLength) {
This logic would accept:

```js
hasSentence('hi                                   '); // true
```

2017-05-21 15:14 UTC, msafih commented on client/src/redux/actions.ts
> +  setSubmitFormValues: (payload: object) => ({type: 'setSubmitFormValues', payload}),
Don't we have linting against that? If not, we should.

2017-05-22 05:13 UTC, JavaScriptErika commented on client/src/redux/actions.ts
> +  setSubmitFormValues: (payload: object) => ({type: 'setSubmitFormValues', payload}),
I'll make that change. @msafih, I did not receive linting errors typing out `object`.

2017-05-22 05:16 UTC, JavaScriptErika commented on client/src/utils/utils.ts
> +export function isValidEmail(email: string): boolean {
That's great to know!

2017-05-22 05:21 UTC, JavaScriptErika commented on client/src/utils/utils.ts
> +  const ePattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/
I'll make changes to that variable name, and keep the naming convention in mind for the future!

Thank you for bringing the regex pattern up to my attention - we most certainly need to include non-English characters and characters such as `+` for emails.

2017-05-22 05:22 UTC, JavaScriptErika commented on client/src/utils/utils.ts
> +  if (message.trim().length !== 0 && message.length > minLength) {
Noooo! haha, ok - I will revisit this logic so that scenario doesn't return true.

2017-05-23 13:50 UTC, levsthings commented on client/src/redux/actions.ts
> +  setSubmitFormValues: (payload: {}) => ({type: 'setSubmitFormValues', payload}),
Don't forget, the `payload: {}` is only temporary. If you notice, whenever the type is `object` we have to write an interface for it and use that interface there as the type.

2017-05-23 13:51 UTC, levsthings commented on client/src/redux/reducers.ts
> +  submitFormValues: {email: string, message: string}
Same thing here, the interface you can write may also define the type of `submitFormValues` here.

2017-05-24 01:47 UTC, JavaScriptErika commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +export interface ContactFormData {
Exporting the `ContactFormData interface` temporarily in this file until @levsthings finds a place for it in the `typings` directory.

2017-05-24 02:12 UTC, JavaScriptErika commented on client/src/utils/utils.ts
> +export function isValidEmail(email: string): boolean {
@msafih would you prefer if I remove the return type?

2017-05-26 02:46 UTC, msafih commented on client/src/utils/utils.ts
> +export function isValidEmail(email: string): boolean {
@JavaScriptErika Your call. I don't have an opinion on this.

2017-05-27 07:16 UTC, JavaScriptErika commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +import {pick, isValidEmail, hasSentence} from '../../utils/utils'
Found the linting error and will fix and include in next commit: `import {hasSentence, isValidEmail, pick} from '../../utils/utils'`

2017-06-20 03:39 UTC, wholesomedev requested changes

2017-06-20 03:39 UTC, msafih commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +)(ContactUsFormClass)
@JavaScriptErika I think you did an excellent job in setting the blur state on the input (this exercise gives you insight into what 3rd party libraries like `redux-form` basically do). However, I don't think we should merge this code in this shape. I think it's time we bring in a 3rd party library that will manage these form properties for us. What do you think?

2017-06-20 03:39 UTC, msafih commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +    fetch('https://jsonplaceholder.typicode.com/posts/1').then((response) => {
It would be cleaner to move this to Redux Sagas

2017-06-20 12:59 UTC, JavaScriptErika commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +    fetch('https://jsonplaceholder.typicode.com/posts/1').then((response) => {
Great - I'll look into making that move

2017-06-20 13:01 UTC, JavaScriptErika commented on client/src/pages/contactUsForm/contactUsForm.tsx
> +)(ContactUsFormClass)
Thank you @msafih! It is very beneficial to gain the insight with this exercise and see what's going on underneath the hood with the logic. I agree with you - let's bring on the 3rd part library!

2017-07-14 19:54 UTC, forabi commented
@JavaScriptErika Any progress on this? Do you need any help intergrating Redux Form?

2017-07-15 02:36 UTC, msafih commented
@forabi Yesterday @JavaScriptErika told me that she's stepping down. She's done a great job with this so far, so we can finish it off when the time is right. I guess for now we can leave it as-is while we work on other areas?

2017-07-15 07:04 UTC, forabi commented
@msafih Yes, we can work on this later.

2017-07-15 16:40 UTC, JavaScriptErika commented
Thank you @msafih! I am more than happy to answer any questions you or @forabi may have about the form when you guys come back to it.

2017-11-25 12:51 UTC, forabi commented
We made a lot of changes to directory structure and the libraries we are using since this PR was started. Let's close this.

2017-11-25 12:51 UTC, closed without merging