Add events to 'Notable Person Page'
hollowverse-archive/hollowverse pull request #78
Opened 2017-05-15 11:43 UTC by levsthings

- [ ] Implement Events
- [ ] Connect to Firebase Backend
- [ ] Make a final design pass

2017-05-17 21:51 UTC, levsthings commented
> - [x] Design and implement events on Notable Person Page
> <s>Design and implement "add events" feature on Notable Person Page</s> _Out of v1 scope._
> - [ ] Connect to Firebase back-end
> - [ ] Make a final design pass

Currently I'm on the last item, I'm commenting out the unnecessary functionality like login, hamburger. The design of NP page for the pilot v1 is almost ready, what will be the source of our data for the particular pilot notable person?

2017-05-18 03:20 UTC, msafih commented
@levsthings I'm thinking we can manually fill out the Firebase database, and load the data on the NPs page?

2017-05-18 06:29 UTC, levsthings commented
Sounds good to me, I've transferred the dummy data to Firebase database, we'll pull from there.

2017-05-21 15:49 UTC, wholesomedev requested changes

2017-05-21 15:49 UTC, msafih commented on client/src/common.styles.ts
> +}
As we discussed, I think it's better to have a name of the color that's in the array.

2017-05-21 15:49 UTC, msafih commented on client/src/globalStyles.css
> +    transform: translate3d(0, 20%, 0); } }
Are we gonna be able to move these to Aphrodite eventually?

2017-05-21 15:49 UTC, msafih commented on client/src/pages/notablePerson/events.styles.ts
> +})
Should we start moving some things to `common.styles`? @JavaScriptErika will want to use some of these things in #76 to style it?

2017-05-21 15:49 UTC, msafih commented on client/src/pages/notablePerson/events.tsx
> +      eventId: number,
I think the word `event` is redundant here.

2017-05-21 17:13 UTC, levsthings commented on client/src/globalStyles.css
> +    transform: translate3d(0, 20%, 0); } }
Yeah, this is the last bit of code which relies on CSS, this will be removed when I start working on transitions.

2017-05-21 17:14 UTC, levsthings commented on client/src/pages/notablePerson/events.styles.ts
> +})
Yeah, I'll export as much as I can for common.styles before she starts using CSS.

2017-05-21 17:15 UTC, levsthings commented on client/src/pages/notablePerson/events.tsx
> +      eventId: number,
All the redundant prefixes are behind us with the latest schema.

2017-05-21 23:39 UTC, msafih commented on client/src/vendor/firebase.ts
> +    return firebaseDb.ref().child(child).once(
I think `firebaseDb.ref().child(child).once('value')` will return a promise if you don't give it a callback function. Can we use that syntax and use async/await? 

I know that my code above is doing this, but that code is pretty bad and we should clean it up.

2017-05-22 19:53 UTC, levsthings commented
Summary:
- NP page design is ready.
- Data types and schemas are ready both in the codebase and on Firebase.
- We're pulling Events data from Firebase and conditionally rendering.
- Additional data request saga logic is in place for pulling userData for future versions. (For displaying avatar, display name under Events, on Header etc..)
- First iteration of `shadowComponents` for high fidelity loading is ready.

I think this is enough for this PR to be reviewed and merged.

Additional tasks that surfaced while working on this PR will be handled in separate PRs:

- Work on router per our discussions and pull NP data with route parameters.
- If `shadowComponents` will be kept, send a PR to improve their design and usage.
- Make a final design pass on all pages and components right before we reach v1.
- Rewrite all Firebase functions with `async/await` 
- Rewrite Redux file/folder structure.

2017-05-22 19:58 UTC, levsthings commented on client/src/common.styles.ts
> +}
Updated as per our discussions.

2017-05-22 20:03 UTC, levsthings commented on client/src/pages/notablePerson/events.styles.ts
> +})
I think the container level styles, typography styles and palettes will be enough for the commons for now. I haven't exported anything else because the rest are really specific for Notable Person. As I'm writing my custom CSS solutions, reusability of  minor details shouldn't be an issue. Also in terms of page diversity, we don't have many templates, I'd like to keep top-level styles in `common.styles` and template specific implementations on their respective `.styles` files.

2017-05-23 04:27 UTC, wholesomedev requested changes

2017-05-23 04:27 UTC, wholesomedev commented on client/src/app/app.styles.ts
> +const {shadesOfWhite} = palette
Nit: maybe should be called `shadesOfGray` because usually white is thought of as binary and without shades...just a suggestion :)

2017-05-23 04:27 UTC, msafih commented on client/src/app/header.styles.ts
> +const {shadesOfBlack} = palette
But then there's `shadesOfBlack`, so what's the difference between `shadesOfGray` and `shadesOfBlack` 🤔

2017-05-23 04:27 UTC, msafih commented on client/src/components/shadowComponent.styles.ts
> +    width: '200px',
Generally speaking, is it possible to avoid fixed widths and heights and use percentages (I'm wondering if such approach is even possible)?

The other thing, why does the shadow photo have potentially different width and height compared to the actual photo?

2017-05-23 04:27 UTC, msafih commented on client/src/components/shadowComponent.tsx
> +export const ShadowComponent = ShadowComponentClass
I think it would be simpler to create a `notablePersonShadowComponent.ts` that lives alongside `notablePerson.ts`. I don't see a need a higher abstraction yet.

2017-05-23 04:27 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.tsx
> +      this.renderNotablePerson()
`render` here just calls `renderNotablePerson`, so maybe rename `renderNotablePerson` to `render` and delete the other `render`?

2017-05-23 04:27 UTC, msafih commented on client/src/redux/sagas.ts
> +    console.log(firebaseResponse)
We're not gonna have any `console.logs` in production, right?

2017-05-23 11:30 UTC, levsthings commented on client/src/app/header.styles.ts
> +const {shadesOfBlack} = palette
Yeah, categorization via the root color is not perfect like this. That's why I had them named as `background.palette` and `typography.palette` before. You think we should go back to that?

2017-05-23 11:37 UTC, levsthings commented on client/src/components/shadowComponent.styles.ts
> +    width: '200px',
This CSS used for drawing a precise circle and things such as avatars, profile photos are defined with px values.
The values of shadow components will be different than the originals because they're mostly `spans` doing magic, they don't have nice normalized margins in contrast to real markup with things like `h1, h2, img` etc..

2017-05-23 11:38 UTC, levsthings commented on client/src/redux/sagas.ts
> +    console.log(firebaseResponse)
Oh forgot to clean this function because it was unused.

2017-05-23 12:15 UTC, levsthings commented on client/src/components/shadowComponent.styles.ts
> +    width: '200px',
Also note that we're designing for the smallest screen so we're fully safe in terms of responsiveness.

2017-05-23 13:56 UTC, levsthings commented
Requested changes are ready, the only thing remains is the naming of the color arrays.

2017-05-23 13:56 UTC, levsthings commented on client/src/app/header.styles.ts
> +const {shadesOfBlack} = palette
![untitled-1](https://cloud.githubusercontent.com/assets/20170364/26357693/ce24cbb8-3fd8-11e7-8bd1-3e37264f6432.png)

2017-05-24 04:44 UTC, wholesomedev submitted a review, later dismissed
I had one small non-blocking comment. The rest LGTM!

2017-05-24 04:44 UTC, msafih commented on client/src/pages/notablePerson/notablePerson.tsx
> +      return <ShadowComponent type='NotablePerson'/> // Loading? Grayed Out Components? WIP.
If this is a shadow component specifically for the notable person, you don't need to give it a type, right? You can just render it.

2017-05-24 04:47 UTC, msafih commented
Looks like there are linting issues.

2017-05-24 11:35 UTC, levsthings commented
@msafih Yesterday I noticed that there were some new linting rules that appeared while working on HollowBot. It started asking for alphabetical imports, I thought it was something to do with my settings there. Today, the same issue is is happening on Hollowverse. 

Build fails due to:
`interface name must start with a capitalized I`
`Import sources within a group must be alphabetized`

Strange thing is I don't see this linting errors locally. Did you update these rules yourself or is there something unintended going on?

2017-05-24 17:07 UTC, wholesomedev approved these changes
LGTM

2017-05-24 17:07 UTC, merged