Refactor actively used promises in the codebase
hollowverse-archive/hollowverse pull request #94
Opened 2017-05-25 12:15 UTC by levsthings

I'll be refactoring all the promises that are actively wired and used by the project.

2017-05-25 19:50 UTC, msafih commented on client/src/vendor/facebook.ts
> +    return await FB.logout((response) => {
Does this syntax actually work? If so, why don't you use the same with the other functions above?

2017-05-25 20:06 UTC, levsthings commented on client/src/vendor/facebook.ts
> +    return await FB.logout((response) => {
All of them work like a charm, the only problem is the `login` function for now.

2017-05-26 02:02 UTC, msafih commented on client/src/vendor/facebook.ts
> +    return await FB.logout((response) => {
@levsthings Why is the `login` one different, what's problematic about it?

2017-05-28 13:35 UTC, levsthings commented on client/src/vendor/facebook.ts
> +    return await FB.logout((response) => {
Unlike all the other functions in `facebook.ts`, in `login` we rely on `resolve/reject` to prevent a login loop. Check out the latest version.

2017-05-28 16:00 UTC, levsthings commented on client/src/vendor/facebook.ts
> +    return await FB.logout((response) => {
The common practice for times when you need to convert a callback to a promise is as follows:

```
function getQuote() {
  var quote;
 
  return new Promise(function(resolve, reject) {
    request('http://ron-swanson-quotes.herokuapp.com/v2/quotes', function(error, response, body) {
      quote = body;
 
      resolve(quote);
    });
  });
}
 
async function main() {
  var quote = await getQuote();
  console.log(quote);
}
```

My implementation is similar but I'm not extracting the Promise to a separate function, I'm handling everything in the same block.

2017-05-28 18:18 UTC, levsthings commented on client/src/vendor/facebook.ts
> +    return await FB.logout((response) => {
I have updated the implementation in `09fbc96` to be the same as the example I've pasted in the previous comment.

The reasons for extracting the promise into another function:
1- More common way of doing things.
2- Async/Await block stays synchronous looking.
3- `Firebase.ts` will also have similar implementations with longer code blocks, they'll benefit from extracted promises, I want to keep the style consistent.

2017-05-31 04:34 UTC, msafih commented
Hey @levsthings Is this ready? What are the next steps on it?

2017-05-31 11:26 UTC, levsthings commented
@msafih I forgot to request a review on this, could you take a look at the last iteration? I don't have any other ideas for this PR, I'll leave the decision up to you for any potential next steps.

2017-06-01 03:14 UTC, msafih commented
I would suggest that we create a utility function that promisifies the methods of the Facebook SDK and then convert all those functions into async await.

We might lose some type-safety, but we can figure out how to improve that later.

2017-06-01 12:45 UTC, levsthings commented
At the moment there are two Facebook SDK methods that returns promises. If I try to extract promises like I did in the first iteration, I feel like we'll go full circle back. Can you please give me an example of the utility function you wanted using `login` as an example?

2017-06-01 17:21 UTC, msafih commented
@levsthings 

I made this quick and dirty, I can clean it up later if you want, but it conveys the idea I think:

```js
  function giveMeCallback(callback) {
    setTimeout(() => {
      callback('this is the results')
    }, 1000)
  }

  // giveMeCallback((results, err) => {
  //   if (err) {
  //     console.log(err)
  //   } else {
  //     console.log(results)
  //   }
  // })

  function promisify(func) {
    return function() {
      return new Promise((resolve, reject) => {
        func((results, err) => {
          if (err) {
            reject(err)
          } else {
            resolve(results)
          }
        })
      })
    }
  }

  const giveMeCallbackPromise = promisify(giveMeCallback)

  giveMeCallbackPromise().then((results) => {
    console.log(results)
  })
```

2017-06-01 19:06 UTC, levsthings commented
This was a good example and if you check my last commit, you can see how I implemented it. It works without an issue however the `async/await` I've used there became redundant again. Any ideas on this?

I like the approach of node style "promisify" utilities but we still haven't been able to find a place for `async/await` :grin:

2017-06-01 19:32 UTC, levsthings commented
https://github.com/hollowverse/hollowverse/blob/refactor-used-promises/client/src/vendor/facebook.ts
In general I really like node style "promisfy" utilities but it's weird here. Can you check this out and let me know if this is similar to what you had in mind? The problem with this is `async/await` is still redundant in this approach. `console.log()` on the results works but sagas don't work as expected in this setup and we lost the types. Am I missing something?

2017-06-01 20:23 UTC, wholesomedev requested changes

2017-06-01 20:23 UTC, msafih commented on client/src/vendor/facebook.ts
>  }
@levsthings This doesn't look quite right. The idea is to do something like this:

```js
FB.getLoginStatus = promisify(FB.getLoginStatus)
// FB.login = promisify(FB.login)
// FB.logout = promisify(FB.logout)
// Etc...

async function getLoginStatus() {
  try {
    const loginStatus = await FB.getLoginStatus()
    
    return loginStatus
  } catch(e) {
    throw e
  }
}
```

We are converting FB SDKs methods to promises so that we can use them inside async/await. Promises can be used in async/await syntax. Callbacks cannot.

2017-06-01 20:33 UTC, levsthings commented on client/src/vendor/facebook.ts
>  }
Oh now I see.

2017-06-14 11:28 UTC, levsthings commented
@msafih Could you please review the final status of this for me?

Here's what happened so far: 

All of FB methods other than FB.init are promisifed with our utility function, I've tested all of them, login/logout/getLoginStatus functionality works as intended. FB.init doesn't play well with the promisification, so I'm calling that synchronously.

Let me know what you think but don't merge it even if you like everything because I need to comment out the login/logout button before merging as we don't need it for v1.

2017-06-15 03:24 UTC, wholesomedev requested changes
I've left a few comments on the Facebook functions and took the liberty to comment on Firebase functions too. Hope that's ok.

2017-06-15 03:24 UTC, msafih commented on client/src/vendor/firebase.ts
> +  }
Can this function be written to utilize async/await more?

```js
export async function login(payload) {
  try {
    await new Promise((resolve) => {
      const unsubscribe = firebaseAuth.onAuthStateChanged((firebaseUser) => {
        unsubscribe()
        
        resolve(firebaseUser)
      })
    })
    
    const credential = firebase.auth.FacebookAuthProvider.credential(payload.authResponse.accessToken)
    
    await firebaseAuth.signInWithCredential(credential)
  } catch (err) {
    throw err
  }
}
```

...but let's forget about the async/await issue for a second. There seems to be something wrong with this function. The call to `firebaseAuth.onAuthStateChanged`, which gives us the `firebaseUser`, we don't seem to be doing anything with this `firebaseUser`. (I know this is my code, so I screwed up.) 

I think it maybe possible to rewrite this function to even be the following...

```js
export async function login(payload) {
  try {
    const credential = firebase.auth.FacebookAuthProvider.credential(payload.authResponse.accessToken)
    
    await firebaseAuth.signInWithCredential(credential)
  } catch (err) {
    throw err
  }
}
```

...right?

2017-06-15 03:24 UTC, msafih commented on client/src/vendor/firebase.ts
> +  }
Can this function be rewritten as such?

```js
  export async function userExists(user) {
    try {
      const usersReference = firebaseDb.ref('users')
      const userSnapshot = await usersReference.child(user.uid).once('value')
      const userExists = userSnapshot.val() !== null
      
      return userExists
    } catch (err) {
      throw err
    }
  }
```

2017-06-15 03:24 UTC, msafih commented on client/src/utils/utils.ts
> +
Are we going to add types to this function?

2017-06-15 03:24 UTC, msafih commented on client/src/redux/sagas.ts
> +    const sdk = yield facebook.initSdk()
If `facebook.initSdk()` returns `void` and it's not a promise or async/await, then this `sdk` variable will always be `undefined` and `yield` is not really doing anything. This could cause a race condition where we execute code assuming the SDK has been initialized but it hasn't. Can we implement something like [this solution](https://stackoverflow.com/a/11274607/604296) in the Facebook SDK init function to eliminate any possible race condition?

2017-06-15 03:24 UTC, msafih commented on client/src/vendor/firebase.ts
>  }
Can this function also be rewritten to utilize async/await?

2017-07-04 03:33 UTC, closed without merging